### ISSUE TITLE
What's the store?

### ISSUE THREAD

**Issue by Directory** [kolbma/rocket-governor#5]
From by brief look at Governor it seems it stores entirely in memory using atomics for multi threaded compatibility. And therefor I assume that makes it compatible with multiple rocket workers. Is it possible that a different store is used? One that uses redis preferably that way rates are tracked even if the server is restarted or if there where multiple horizontal instances of the rocket server. 

If this is simply a limitation of governor then I understand not much can be done.

**Comment by kolbma** [comment]
Yes, currently it uses https://docs.rs/governor/latest/governor/state/keyed/trait.ShrinkableKeyedStateStore.html.  
With implementing a custom https://docs.rs/governor/latest/governor/state/trait.StateStore.html it would be possible to use something else, but it is not possible to use it right now in rocket-governor.  
There is no way to change the above fix coded statestore.
Of course this could be changed, but not sure when I can do it, and since I don't have the code anylonger in my head I can't say right now what might be the way I'd like to implement it.

**Comment by Directory** [comment]
I understand. Another consideration is opening a new redis connection per every request is inefficient and would require a pooler. And what to use as the key since ip addresses aren't always what's desired. Either way i ended up making my own rate limit implemention from scratch using a redis pool and rocket request guard.
